version: '3.8'

services:
  eureka-service:
    build:
      context: ./eureka-service
    container_name: eureka-service
    ports:
      - "8761:8761"
    networks:
      - book-bazaar-net
    environment:
      - SPRING_PROFILES_ACTIVE=default

  catalog-service:
    build:
      context: ./catalog-service
    container_name: catalog-service
    ports:
      - "8081:8081"
    networks:
      - book-bazaar-net
    depends_on:
      - eureka-service
    environment:
      - SPRING_PROFILES_ACTIVE=default

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "8082:8082"
    networks:
      - book-bazaar-net
    depends_on:
      - eureka-service
    environment:
      - SPRING_PROFILES_ACTIVE=default

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bookbazaar
      POSTGRES_USER: bookuser
      POSTGRES_PASSWORD: bookpass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - book-bazaar-net

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - book-bazaar-net

networks:
  book-bazaar-net:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  kafka-data: